[package]
name = "docker_to_uefi_bootable_image"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tempfile = "3"
structopt = "0.3"
uuid = { version = "0.8", features = [ "serde", "v4" ] }

