FROM mongo:4

RUN apt update -y
RUN apt install -y \
    vim python3 python3-virtualenv mongocli \
    cloud-init openssh-server sudo \
    iputils-ping bind9-dnsutils netcat tcpdump

RUN apt purge -y build-essential && apt autoremove -y && rm -rf /var/lib/apt/lists/*

